### ISSUE TITLE
[Bug] Too many intros?

### ISSUE THREAD

**Issue by DRSDavidSoft** [Master-64/Shrek-2.2#2]
**Describe the bug**
Man, why did you add so many unskippable intro videos to the start of the game? 😂 Is there a way to skip them at launch, other than deleting the `.bik` files?

**To Reproduce**
1. Open the game
2. Press `Space` to skip

**Expected behavior**
The added intros are skipped

**Screenshots**
N/A

**Comment by DRSDavidSoft** [comment]
**Update:** Never mind, discovered that the `Esc` key must be used instead.

**Comment by Master-64** [comment]
This will be addressed in the future. I understand there's a need for making it easy to skip all movie cutscenes at once. At the moment, it's possible to disable the intro movies in the options menu, however I do wish to make it possible to make skipping all the movies possible with the cutscene skip button, like everyone would've originally expected.

**Comment by DRSDavidSoft** [comment]
@Master-64 Thanks for the update, looking forward to that!

It's alwyas hreat to hear from you, I hope the development of it goes smooth. Excited for future news!
